# Generated by Django 4.1.7 on 2023-03-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(max_length=127),
        ),
    ]
