# Generated by Django 4.1.7 on 2023-03-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_picture_products_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.FloatField(),
        ),
    ]
